### ISSUE TITLE
'str' object has no attribute 'resolve'

### ISSUE THREAD

**Issue by collindutter** [griptape-ai/griptape-nodes#2856]
Regression from https://github.com/griptape-ai/griptape-nodes/pull/2850
```
12:28:12
    '__init__.py'                                           | |
12:28:12
| |  fullname = 'C:\\Users\\admin\\Documents\\griptape-nodes-desktop\\_use�
12:28:12
| |      path = WindowsPath('C:/Users/admin/Documents/griptape-nodes-deskt� | |
12:28:12
| |   results =
12:28:12
 <generator object walk at 0x000001F087537400>               | |
12:28:12
| -nodes\Lib\site-packages\griptape_nodes\cli\commands\libraries.py:108 in    |
12:28:12
| _remove_readonly                                                            |
12:28:12
|   105     if not GriptapeNodes.OSManager().is_windows():                    |
12:28:12
|   106         return                                                        |
12:28:12
|   107                                                                       |
12:28:12
 > 108     long_path = Path(GriptapeNodes.OSManager().normalize_path_for_pla |
12:28:12
|   109                                                                       |
12:28:12
|   110     try:                                                              |
12:28:12
|   111         Path.chmod(long_path, stat.S_IWRITE)                          |
12:28:12
                                                                            |
12:28:12
| | excinfo
12:28:12
 = FileNotFoundError(2, 'The system cannot find the path         | |
12:28:12
| |           specified'
12:28:12
)                                                   | |
12:28:12
| |    func = <built-in function unlink>
12:28:12
                                    | |
12:28:12
| |    path = 'C:\\Users\\admin\\Documents\\griptape-nodes-desktop\\_userd� | |
12:28:12
| -nodes\Lib\site-packages\griptape_nodes\retained_mode\managers\os_manager.p 
12:28:12
| y:194 in normalize_path_for_platform                                        |
12:28:12
|    191         Returns:                                                     |
12:28:12
|    192 
12:28:12
            String representation of path, with Windows long path pr |
12:28:12
|    193         """                                                          |
12:28:12
| >  194         path_str = str(path.resolve())                               |
12:28:12
|    195                                                                      |
12:28:12
|    196         # Windows long path handling (paths > WINDOWS_MAX_PATH chars |
12:28:12
|    197         if self.is_windows() and len(path_str) > WINDOWS_MAX_PATH an |
12:28:12
| | path = 
12:28:12
'C:\\Users\\admin\\Documents\\griptape-nodes-desktop\\_userdata� | |
12:28:12
| | self = <griptape_nodes.retained_mode.managers.os_manager.OSManager      |
12:28:12
| |        object at 0x000001F085E1ED80>                                    | |
12:28:12
| +-------------------------------------------------------------------------+
12:28:12
AttributeError: 'str' object has no attribute 'resolve'
```
